### ISSUE TITLE
Travis CI integration: Wrong committer name

### ISSUE THREAD

**Issue by lezsakdomi** [nonnymoose/xsr#82]
Here's a recording demonstrating the issue:
[Untitled Recording.pdf](https://github.com/nonnymoose/xsr/files/1608734/Untitled.Recording.pdf)

(Sorry for the quality; it looks like we should provide a PDF storage engine for github issue attachments 😄)

**Comment by nonnymoose** [comment]
Sorry. I didn't realize you wanted me to use a token from the bot account. I'll fix that.
Also LOL you used XSR :)

**Comment by nonnymoose** [comment]
@lezsakdomi Can you email me the username and password for the bot? For some reason, Github will only let me reset my own password, even though the bot's registered to my email.

**Comment by lezsakdomi** [comment]
@nonnymoose Sorry, I forgot to mention, that I've registered you with the email-address `<google_account>+github-nonnymoos-xsr-machine-user@gmail.com` rather than `<google_account>@gmail.com`.

For example, mine is `lezsakdomi1+github-nonnymoos-xsr-machine-user@gmail.com`.
Altough you didn't verify it yet.

Anyways, I'm going to send a recovery link to you by email.

**Comment by nonnymoose** [comment]
@lezsakdomi I've attached the email I got. It asks me to verify the email, and then it asks for the password, which I can't reset, because I haven't verified the email :(.
[Gmail - [GitHub] Please verify your email address_.pdf](https://github.com/nonnymoose/xsr/files/1608977/Gmail.-.GitHub.Please.verify.your.email.address_.pdf)

**Comment by nonnymoose** [comment]
This should have been fixed now.

**Comment by lezsakdomi** [comment]
Umm, it looks like you forgot to update a setting.
https://travis-ci.org/nonnymoose/xsr/jobs/325885211#L509

**Comment by nonnymoose** [comment]
That's really odd. nonnymoose-xsr-machine-user can push...

**Comment by nonnymoose** [comment]
Oh wait, forgot public repo access.
It's fixed now.

**Comment by lezsakdomi** [comment]
@nonnymoose Did you try pushing to the indicated URL manually? Maybe just the token has insufficient rights.

**Comment by lezsakdomi** [comment]
Maybe time to migrate to CircleCI :D

**Comment by nonnymoose** [comment]
@lezsakdomi The token _did_ have insufficient rights. I have actually already fixed it.

**Comment by lezsakdomi** [comment]
Ohh, sorry, GitHub forgot to show me your comments. Wow, I didn't see like this before.

**Comment by nonnymoose** [comment]
No problem! That happens to me too sometimes.
